name: CICD 

#manually click delever 
on:
  workflow_dispatch: 
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        run: echo "code clone from GitHub"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build a docker file
        run: echo "build a docker image"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test hoga
        run: echo "testing ho rha hi "

  deploy:
    needs: [test,build]
    runs-on: ubuntu-latest
    steps:
      - name: deployment
        run: echo "deploying"
      
