name: Code Quality Check

on:
    workflow_call:


jobs:
    code-quality-check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11","3.12","3.13","3.14"]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: setup python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-verion: ${{ matrix.python-version }}
                cache: 'pip'

            - name: install dependencies
              run: pip install -r requirements.txt

              
            - name: run linter
              run: flake8 app.py

            - name: run SAST 
              run: bandit -r app.py
