name: Dependency Check

on:
    workflow_call:
    

jobs:
    dependency-check:
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11","3.12","3.13","3.14"]
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
        
            - name: setup python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: install pip audit
              run: pip install pip-audit

            - name: audit dependencies
              run: pip-audit -r requirements.txt