name: Dependency Check

on:
    workflow_call:
    

jobs:
    dependency-check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4