#this is the action name
name: hello

#run triggers
on:
  workflow_dispatch:
    

#these are the workflow
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user 
        run: echo "Hello usesr  "
      - name: print current user name 
        run: echo "curret user $USER"
      
