name: Secrets Scan

on: 
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              